<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Themes.Simple" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.0"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.1.0">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <PropertyGroup Condition="'$(OS)' != '' and $([System.String]::Copy('$(OS)').ToLower().StartsWith('win'))">
        <DefineConstants>WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(OS)' == 'Unix'">
        <DefineConstants>LINUX</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <UpToDateCheckInput Remove="Style\Styles1.axaml" />
    </ItemGroup>
    <Target Name="CopyNeutronBinary" AfterTargets="Build">
        <ItemGroup>
            <NeutronBinary Include="..\NeutronRuntime\neutron.exe" />
            <NeutronBinary Include="..\NeutronRuntime\neutron" />
        </ItemGroup>
        <Copy
            SourceFiles="@(NeutronBinary)"
            DestinationFolder="$(OutDir)"
            SkipUnchangedFiles="true" />
    </Target>
</Project>
